### ISSUE TITLE
convert hashtags in markdown to ssb url

### ISSUE THREAD

**Issue by av8ta** [av8ta/extension-agregore-render-ssb-posts#1]

**Comment by av8ta** [comment]
what to do with hashtags?
I believe they don't have a canonical uri??
so, best to leave to app devs?

would be good to show channel messages though...
but don't wish to make a non-standard url...

agregore currently appends the #music href as expected:

```ssb://message/sha256/xyz===#music```

it should probably be a route though:

```ssb://message/sha256/xyz===/#music```

what do routes mean in terms of ssb uri ? todo: re-read the uri spec and catch up with discussion on the scuttleverse, this has likely been discussed in the uri megathread 

note though, that channels aren't a protocol thing,
they're a patchwork construct that is ubiquitous in the ecosystem
todo: research what the ecosystem is doing

**Comment by RangerMauve** [comment]
Would it be possible to disable the channels function in ssb-markdown for now? Or just leave whatever is the default and consider it broken? 😅

**Comment by av8ta** [comment]
Yes! 😂
